server:
  port: 9001

spring:
  application:
    name: ADDRESS-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://bacd.spcluster.tk/eureka
  instance:
    hostname: adesssdadacd
