server:
  port: 9002

spring:
  application:
    name: APPOINTMENT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://backend.spcluster.tk/
  instance:
    hostname: appointment
