apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: frontend.spcluster.tk
    http:
     paths:
     - path: /
       pathType: Prefix
       backend:
         service:
           name: cluster-ip-frontend
           port:
             number: 80
  - host: mockserver.spcluster.tk
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: cluster-ip-mockserver
              port:
                number: 3005
  - host: backend.spcluster.tk
    http:
      paths:
        - path: /$
          pathType: Exact
          backend:
            service:
              name: service-registry
              port:
                number: 8761
        - path: /eureka
          pathType: Prefix
          backend:
            service:
              name: service-registry
              port:
                number: 8761
        - path: /
          pathType: Prefix
          backend:
            service:
              name: cloud-gateway
              port:
                number: 9191
       
        
        
        # - path: /address
        #   pathType: Prefix
        #   backend:
        #     service:
        #       name: address
        #       port:
        #         number: 9001
        # - path: /appointments
        #   pathType: Prefix
        #   backend:
        #     service:
        #       name: appointment
        #       port:
        #         number: 9002
        # - path: /cards
        #   pathType: Prefix
        #   backend:
        #     service:
        #       name: card
        #       port:
        #         number: 9003
        # - path: /labs
        #   pathType: Prefix
        #   backend:
        #     service:
        #       name: lab
        #       port:
        #         number: 9004
        # - path: /patients
        #   pathType: Prefix
        #   backend:
        #     service:
        #       name: patient
        #       port:
        #         number: 9005
        # - path: /testlabs
        #   pathType: Prefix
        #   backend:
        #     service:
        #       name: test-lab
        #       port:
        #         number: 9006
        # - path: /tests
        #   pathType: Prefix
        #   backend:
        #     service:
        #       name: test
        #       port:
        #         number: 9007
        # - path: /users
        #   pathType: Prefix
        #   backend:
        #     service:
        #       name: user
        #       port:
        #         number: 9008

              

  