server:
  port: 9007

spring:
  application:
    name: TEST-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://backend.spcluster.tk/
  instance:
    hostname: test-service
