name: CI/CD for the mockserver into EKS cluster

on:
  push:
    paths:
      - frontend/db/**
      - .github/workflows/mockserver.yml

jobs:
  build_and_deploy:
     runs-on: ubuntu-latest

     defaults:
       run:
         working-directory: frontend

     steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-npmNode-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npmNode-

      - name: install dependencies
        run: npm install --legacy-peer-deps

      - name: run build
        run: npm run build
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.DOCKERPW }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/db
          file: ./frontend/db/Dockerfile
          push: true
          tags: ghcr.io/${{ secrets.DOCKERUSER }}/mockserver:${{ github.run_number }}

      - name: install kubectl 
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.25.1'
        id: install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: update kube Config file
        run: aws eks update-kubeconfig --name my_cluster --region us-east-1

      - name: Deploy to EKS
        run: |
          cd secrets
          kubectl apply -f ghcrSecret.yml
          cd ../deploymentKube
          kubectl apply -f mockserverDeploy.yml
          cd ../services
          kubectl apply -f clusterIp.yml
          cd ../ingress
          kubectl apply -f ingress.yml

      
